name: NRK Core CSS

headHtml: |
  <script src="https://static.nrk.no/core-icons/latest/core-icons.min.js"></script>
  <script src="https://static.nrk.no/core-components/major/1/core-components.min.js"></script>
  <link rel="stylesheet" href="docs.css">
  <script>
    // Expose JS components to window
    Object.keys(window.coreComponents).forEach(function (key) {
      window['core' + key[0].toUpperCase() + key.slice(1)] = coreComponents[key]
    })
  </script>

assets:
  - docs.css          # Include CSS for documentation
  - core-css.css      # Include core CSS
  - core-css.min.css  # Include core CSS minified as this goes to static.nrk.no

sidebar:
  background: "#3d2351"
  textColor: "#fff"

order:
  - Introduction
  - Layout
